;;; teams4e-navigation-tests.el --- Resume without reloading -*- lexical-binding: t; -*-
(require 'ert)
(require 'teams4e)

(defmacro teams4e-navigation-test (&rest body)
  "Run BODY with isolated live Teams buffers and window state."
  (declare (indent 0))
  `(save-window-excursion
     (let* ((headers (generate-new-buffer " *Teams navigation headers*"))
            (reader (generate-new-buffer " *Teams navigation reader*"))
            (outside (generate-new-buffer " *Teams navigation outside*"))
            (teams4e--recent-buffer-name (buffer-name headers))
            (teams4e--resume-layouts (make-hash-table :test #'eq))
            (teams4e--window-configurations (make-hash-table :test #'eq))
            (teams4e-offline-mode t)
            (teams4e-preview-on-move nil))
       (unwind-protect
           (progn
             (with-current-buffer headers (teams4e-recent-mode))
             (with-current-buffer reader (teams4e-chat-mode))
             (switch-to-buffer outside)
             (delete-other-windows)
             ,@body)
         (dolist (buffer (list headers reader outside))
           (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest teams4e-resume-first-use-loads-exactly-once ()
  (let ((calls 0))
    (cl-letf (((symbol-function 'buffer-list) (lambda (&rest _) nil))
              ((symbol-function 'teams4e-inbox) (lambda () (cl-incf calls))))
      (teams4e-switch-to-buffer)
      (should (= calls 1))
      (teams4e-switch-to-buffer '(4))
      (should (= calls 2)))))

(ert-deftest teams4e-resume-restores-layout-point-and-filter-without-network ()
  (teams4e-navigation-test
    (let ((teams4e--active-query "topic:review unread")
          (teams4e--unread-filter-enabled t)
          (window-min-height 2))
      (switch-to-buffer headers)
      (let ((pane (split-window-below 5)))
        (set-window-buffer pane reader)
        (select-window pane))
      (let ((inhibit-read-only t)) (insert "one\ntwo\nthree\n") (goto-char 6))
      (teams4e--remember-workspace)
      (switch-to-buffer outside)
      (cl-letf (((symbol-function 'buffer-list) (lambda (&rest _) (list reader headers outside)))
                ((symbol-function 'teams4e--run-json)
                 (lambda (&rest _) (ert-fail "Resume initiated a network request")))
                ((symbol-function 'teams4e-inbox)
                 (lambda () (ert-fail "Resume reopened the inbox"))))
        (teams4e-switch-to-buffer))
      (should (eq reader (current-buffer)))
      (should (= 6 (point)))
      (should (get-buffer-window headers))
      (should (= 2 (length (window-list))))
      (should (equal "topic:review unread" teams4e--active-query))
      (should teams4e--unread-filter-enabled)
      (teams4e-quit)
      (should (eq outside (window-buffer (selected-window)))))))

(ert-deftest teams4e-resume-selects-visible-pane-without-rearranging ()
  (teams4e-navigation-test
    (let ((window-min-height 2))
      (set-window-buffer (split-window-below 5) reader))
    (let ((windows (window-list)))
      (cl-letf (((symbol-function 'buffer-list) (lambda (&rest _) (list reader headers))))
        (teams4e-switch-to-buffer))
      (should (eq reader (current-buffer)))
      (should (equal windows (window-list nil nil (car windows)))))))

(ert-deftest teams4e-resume-prefers-org-draft-and-prefix-keeps-text ()
  (teams4e-navigation-test
    (with-current-buffer reader
      (org-mode)
      (setq buffer-read-only nil)
      (setq-local teams4e-compose-edit-mode t)
      (insert "* Unsent reply\nKeep this text.")
      (goto-char 8))
    (let ((calls 0))
      (cl-letf (((symbol-function 'buffer-list) (lambda (&rest _) (list headers reader)))
                ((symbol-function 'teams4e-recent-refresh)
                 (lambda ()
                   (should (eq headers (current-buffer)))
                   (cl-incf calls)
                   (switch-to-buffer headers))))
        (teams4e-switch-to-buffer)
        (should (= calls 0))
        (should (eq reader (current-buffer)))
        (teams4e-switch-to-buffer '(4))
        (should (= calls 1))
        (should (eq reader (current-buffer)))
        (should (= 8 (point)))
        (should (equal "* Unsent reply\nKeep this text." (buffer-string)))))))

(ert-deftest teams4e-resume-prefix-refreshes-current-reader-once ()
  (teams4e-navigation-test
    (let ((calls 0))
      (cl-letf (((symbol-function 'buffer-list) (lambda (&rest _) (list reader headers)))
                ((symbol-function 'teams4e-chat-refresh)
                 (lambda (&rest _) (cl-incf calls))))
        (teams4e-switch-to-buffer '(4))
        (should (eq reader (current-buffer)))
        (should (= calls 1))))))

(ert-deftest teams4e-resume-survives-killed-buffer-without-resurrection ()
  (teams4e-navigation-test
    (switch-to-buffer reader)
    (teams4e--remember-workspace)
    (kill-buffer reader)
    (switch-to-buffer outside)
    (cl-letf (((symbol-function 'buffer-list) (lambda (&rest _) (list reader headers))))
      (teams4e-switch-to-buffer))
    (should (eq headers (current-buffer)))
    (should-not (buffer-live-p reader))))

(ert-deftest teams4e-resume-does-not-run-preview-follow-on-post-command ()
  (let ((this-command 'teams4e-switch-to-buffer)
        (teams4e--inhibit-reader-follow nil))
    (cl-letf (((symbol-function 'teams4e--sync-visible-chat-reader)
               (lambda () (ert-fail "Resume followed headers")))
              ((symbol-function 'teams4e--schedule-preview)
               (lambda () (ert-fail "Resume scheduled a preview"))))
      (teams4e--follow-selected-chat))))

(ert-deftest teams4e-resume-tracking-is-buffer-local ()
  (teams4e-navigation-test
    (with-current-buffer headers
      (should (memq #'teams4e--remember-workspace pre-command-hook)))
    (with-current-buffer outside
      (should-not (memq #'teams4e--remember-workspace pre-command-hook)))))

(provide 'teams4e-navigation-tests)
;;; teams4e-navigation-tests.el ends here
