;;; teams4e-outbox-tests.el --- Offline scheduled send tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'teams4e)
(when (featurep 'evil) (evil-mode 1))

(defmacro teams4e-outbox-test (&rest body)
  (declare (indent 0))
  `(let ((teams4e-draft-directory (make-temp-file "teams4e-schedule-test-" t)))
     (unwind-protect
         (with-temp-buffer
           (teams4e-compose--start-editor '((id . "fixture-chat")) nil)
           (setq teams4e-compose--target '((id . "fixture-chat") (topic . "Fixture")))
           (teams4e-compose--initialize-draft)
           (unwind-protect (progn ,@body)
             (teams4e-compose--delete-draft)))
       (delete-directory teams4e-draft-directory t))))

(ert-deftest teams4e-outbox-reuses-workweek-and-snooze-start ()
  (let* ((teams4e-schedule-work-days nil) (teams4e-schedule-start-time nil)
         (teams4e-workday-start "08:15") (teams4e-calendar-work-days '(0 1 2 3 4))
         (teams4e-schedule-time-zone "Asia/Jerusalem")
         (spec (teams4e-outbox--spec nil)))
    (should (equal (teams4e--get spec 'start) "08:15"))
    (should (equal (teams4e--get spec 'days) [0 1 2 3 4]))
    (should (equal (teams4e--get spec 'zone) "Asia/Jerusalem"))
    (should (equal (teams4e--get spec 'mode) "next"))))

(ert-deftest teams4e-outbox-compose-keys-and-explicit-dispatch ()
  (teams4e-outbox-test
    (should (eq (key-binding (kbd "C-c C-s")) #'teams4e-compose-schedule))
    (should (eq (key-binding (kbd "C-c C-t")) #'teams4e-compose-schedule-at))
    (let (called)
      (cl-letf (((symbol-function 'teams4e-compose-schedule) (lambda (explicit) (setq called explicit))))
        (teams4e-compose-schedule-at))
      (should called))))

(ert-deftest teams4e-outbox-schedule-draft-roundtrip-and-header ()
  (teams4e-outbox-test
    (insert "*Source* text")
    (setq teams4e-compose--schedule '((sendAt . 9999999999) (displayTime . "2286-11-20 07:00 UTC +0000") (zone . "UTC"))
          teams4e-compose--outbox-id "fixture-unique-id" teams4e-compose--outbox-revision 3)
    (teams4e-compose--save-draft)
    (setq teams4e-compose--schedule nil teams4e-compose--outbox-id nil teams4e-compose--outbox-revision nil)
    (let ((inhibit-modification-hooks t)) (erase-buffer))
    (teams4e-compose--initialize-draft)
    (should (equal (buffer-string) "*Source* text"))
    (should (equal teams4e-compose--outbox-id "fixture-unique-id"))
    (should (= teams4e-compose--outbox-revision 3))
    (should (string-match-p "SCHEDULE 2286-11-20 07:00 UTC" header-line-format))
    (should (string-match-p "Fixture" header-line-format))))

(ert-deftest teams4e-outbox-routes-scheduled-draft-not-immediate-send ()
  (teams4e-outbox-test
    (setq teams4e-compose--schedule '((sendAt . 9999999999)))
    (let (queued)
      (cl-letf (((symbol-function 'teams4e-outbox-submit) (lambda () (setq queued t)))
                ((symbol-function 'teams4e-compose-send-now) (lambda () (ert-fail "Immediate send"))))
        (teams4e-compose-send))
      (should queued))))

(ert-deftest teams4e-outbox-freezes-org-source-rendering-and-thread ()
  (teams4e-outbox-test
    (insert "*Hello*\n")
    (setq teams4e-compose--schedule '((sendAt . 9999999999) (displayTime . "future") (zone . "UTC"))
          teams4e-compose--reply-to '((id . "parent") (body . ((content . "original")))))
    (let (payload failure)
      (cl-letf (((symbol-function 'teams4e-outbox--call)
                 (lambda (op args _ok fail)
                   (should (equal op "put"))
                   (setq failure fail payload (json-parse-string (cadr args) :object-type 'alist :null-object nil)))))
        (teams4e-outbox-submit))
      (should buffer-read-only)
      (should teams4e-compose--outbox-busy)
      (should-error (teams4e-compose-send) :type 'user-error)
      (should (equal (teams4e--dig payload 'draft 'body) "*Hello*\n"))
      (should (equal (teams4e--dig payload 'draft 'target 'chatId) "fixture-chat"))
      (should (equal (teams4e--dig payload 'draft 'replyTo 'id) "parent"))
      (should (equal (teams4e--get payload 'contentType) "html"))
      (should (string-match-p "<b>Hello</b>" (teams4e--get payload 'message)))
      (should-not (teams4e--get payload 'revision))
      (funcall failure "network" "fixture failure")
      (should-not buffer-read-only)
      (should-not teams4e-compose--outbox-busy)
      (should (equal (buffer-string) "*Hello*\n"))
      (should teams4e-compose--outbox-id))))

(ert-deftest teams4e-outbox-attachments-rejected-before-any-request ()
  (teams4e-outbox-test
    (setq teams4e-compose--schedule '((sendAt . 9999999999))
          teams4e-compose--attachments '("/fixture/image.png"))
    (cl-letf (((symbol-function 'teams4e-outbox--call) (lambda (&rest _) (ert-fail "Unexpected backend call"))))
      (should-error (teams4e-outbox-submit) :type 'user-error))))

(ert-deftest teams4e-outbox-timer-offline-and-start-failure ()
  (let ((teams4e-outbox--running nil) (teams4e-offline-mode t) calls)
    (cl-letf (((symbol-function 'teams4e-outbox--call) (lambda (&rest _) (setq calls t))))
      (teams4e-outbox--tick))
    (should-not calls))
  (let ((teams4e-outbox--running nil) (teams4e-offline-mode nil))
    (cl-letf (((symbol-function 'teams4e--run-json) (lambda (&rest _) (error "Missing backend"))))
      (teams4e-outbox--tick))
    (should-not teams4e-outbox--running)))

(ert-deftest teams4e-outbox-payload-is-redacted ()
  (should (equal '("--payload" "<content redacted>")
                 (teams4e--redacted-args '("--payload" "private source"))))
  (should (equal "<content redacted>" (teams4e--redacted-detail '("--payload" "private") "private"))))

(ert-deftest teams4e-outbox-open-existing-editor-does-not-change-revision ()
  (let ((buffer (get-buffer-create "*Teams scheduled: fixture-schedule*")))
    (unwind-protect
        (save-window-excursion
          (cl-letf (((symbol-function 'teams4e-outbox--call) (lambda (&rest _) (ert-fail "Already editing"))))
            (teams4e-outbox--edit-id "fixture-schedule"))
          (should (eq buffer (current-buffer))))
      (kill-buffer buffer))))

(ert-deftest teams4e-outbox-evil-action-bindings-work-immediately ()
  (skip-unless (featurep 'evil))
  (with-temp-buffer
    (teams4e-outbox-view-mode)
    (dolist (state '(normal motion))
      (evil-change-state state)
      (should (eq (key-binding (kbd "e")) #'teams4e-outbox-edit))
      (should (eq (key-binding (kbd "d")) #'teams4e-outbox-cancel))
      (should (eq (key-binding (kbd "g")) #'teams4e-outbox)))))

(ert-deftest teams4e-outbox-edit-restores-held-source-and-revision ()
  (let* ((teams4e-draft-directory (make-temp-file "teams4e-held-test-" t))
         (id "fixture-held-source")
         (file (expand-file-name (concat "scheduled-" id ".json") teams4e-draft-directory))
         (target '((kind . "chat") (chatId . "fixture") (label . "Fixture")))
         (draft `((body . "*Original*") (editor . "org") (contentType . "text") (target . ,target)))
         (job `((id . ,id) (revision . 4) (sendAt . 9999999999) (displayTime . "future")
                (zone . "UTC") (draft . ,draft))))
    (unwind-protect
        (save-window-excursion
          (with-temp-file file
            (insert (json-serialize
                     `((body . "*Recovered edit*") (editor . "org") (contentType . "text")
                       (target . ,target) (outboxId . ,id) (outboxRevision . 3)))))
          (cl-letf (((symbol-function 'teams4e-outbox--call)
                     (lambda (op _args ok &optional _fail)
                       (should (equal op "hold")) (funcall ok job))))
            (teams4e-outbox--edit-id id))
          (should (eq major-mode 'org-mode))
          (should (equal (buffer-string) "*Recovered edit*"))
          (should (equal teams4e-compose--draft-file file))
          (should (= teams4e-compose--outbox-revision 4))
          (should (equal (teams4e--chat-id teams4e-compose--target) "fixture"))
          (should teams4e-compose--schedule))
      (when-let ((buffer (get-buffer (format "*Teams scheduled: %s*" id))))
        (with-current-buffer buffer (teams4e-compose--delete-draft))
        (kill-buffer buffer))
      (delete-directory teams4e-draft-directory t))))

(ert-deftest teams4e-outbox-enqueue-success-cleans-draft-and-enables-worker ()
  (teams4e-outbox-test
    (insert "Fixture body")
    (setq teams4e-compose--schedule '((sendAt . 9999999999) (displayTime . "future") (zone . "UTC")))
    (let ((buffer (current-buffer)) enabled killed)
      (cl-letf (((symbol-function 'teams4e-outbox--call)
                 (lambda (_op _args ok &optional _fail)
                   (funcall ok '((state . "scheduled") (displayTime . "future")))))
                ((symbol-function 'teams4e-outbox-mode) (lambda (arg) (setq enabled arg)))
                ((symbol-function 'kill-buffer) (lambda (target) (setq killed target))))
        (teams4e-outbox-submit))
      (should (eq killed buffer))
      (should (= enabled 1))
      (should teams4e-compose--discarded)
      (should-not (file-exists-p teams4e-compose--draft-file)))))

(provide 'teams4e-outbox-tests)
