name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install --yes emacs-nox pandoc
      - name: Check out link-hint test dependency
        uses: actions/checkout@v4
        with:
          repository: noctuid/link-hint.el
          ref: 8fda5dcb9caff5a3c49d22b82e570ac9e29af7dd
          path: .tmp/link-hint
      - name: Check out Avy test dependency
        uses: actions/checkout@v4
        with:
          repository: abo-abo/avy
          ref: 933d1f36cca0f71e4acb5fac707e9ae26c536264
          path: .tmp/avy
      - name: Test link-hint integration
        run: |
          emacs -Q --batch -L . -L .tmp/link-hint -L .tmp/avy \
            -l tests/teams4e-link-hint-tests.el -f ert-run-tests-batch-and-exit
      - name: Check out expand-region test dependency
        uses: actions/checkout@v4
        with:
          repository: magnars/expand-region.el
          ref: 351279272330cae6cecea941b0033a8dd8bcc4e8
          path: .tmp/expand-region
      - name: Check out Evil test dependency
        uses: actions/checkout@v4
        with:
          repository: emacs-evil/evil
          ref: 6a3e1ddd04ac504a016590940d0af2a3361b9efd
          path: .tmp/evil
      - name: Test message selection integration
        run: |
          emacs -Q --batch -L . -L .tmp/expand-region -L .tmp/evil \
            -l tests/teams4e-selection-tests.el -f ert-run-tests-batch-and-exit
      - name: Check out Markdown test dependency
        uses: actions/checkout@v4
        with:
          repository: jrblevin/markdown-mode
          ref: 76cb4ffecfdf95ee769e5cb4608e04202c3c1521
          path: .tmp/markdown-mode
      - name: Test Org and Markdown composition with Evil
        run: |
          emacs -Q --batch -L . -L .tmp/evil -L .tmp/markdown-mode \
            -l evil -l markdown-mode -l tests/teams4e-compose-tests.el \
            -f ert-run-tests-batch-and-exit
      - name: Run tests
        run: |
          make test
          make compile
